version: '3.9'

services:
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: workradius
    volumes:
      - mongo-data:/data/db
    networks:
      - workradius

  server:
    image: saurabhyadav01/workradius-server:v1.0.0
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      - MONGO_URI=mongodb+srv://saurabhyadavairth_db_user:ACgPu01XX5A4bKwW@assingment.n3vmx4p.mongodb.net/?appName=Assingment
      - CLIENT_URL=13.200.39.165
      - PORT=5001
    depends_on:
      - mongo
    ports:
      - '5001:5001'
    networks:
      - workradius

  client:
    image: saurabhyadav01/workradius-client:v1.0.0
    restart: unless-stopped
    env_file:
      - ./client/.env
    environment:
      - VITE_API_URL=https://13.200.39.165/api/v1
      - VITE_SOCKET_URL=wss://13.200.39.165
    networks:
      - workradius

  proxy:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on:
      - client
      - server
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - workradius

volumes:
  mongo-data:

networks:
  workradius:
    driver: bridge

